import React, { useState } from 'react';
import { LoremIpsum } from 'react-lorem-ipsum';
import Template from './Template';

export default function LandingPage() {
  const user = JSON.parse(sessionStorage.getItem('user'));
  const [counter, setCounter] = useState(1);

  return (
    <Template>
      <div>
        <div>
          <p>
            The articles have been generated by the user{' '}
            <span className="user-decoration">{user.username}</span> {counter}{' '}
            time
            {counter > 1 && 's'}.
          </p>
          <button onClick={() => setCounter((counter) => counter + 1)}>
            Generate new articles
          </button>
        </div>
        <div className="articles-wrapper">
          <LoremIpsum p={3} />
        </div>
      </div>
    </Template>
  );
}
